name: NFS-Storage
description: NFS Server
version: 0.0.1
keywords:
  - nfs-server
sources:
  - https://github.hpe.com/abhishek-samuel/common-utilities
home: https://github.hpe.com/abhishek-samuel/common-utilities
maintainers:
  - name: Abhishek Samuel
    email: abhishek.samuel@hpe.com
