conf:
  metrics:
    pv:
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      mountPath: '/pv/metrics'
      storageClassName: 'metrics-storage-class'
      claimName: 'metrics-pvc'
    deployment:
      namespace: 'metrics'

  logging:
    pv:
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      mountPath: '/pv/logging'
      storageClassName: 'logging-storage-class'
      claimName: 'logging-pvc'
    deployment:
      namespace: 'logging'

  dockerRegistry:
    pv:
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      mountPath: '/pv/docker-registry'
      storageClassName: 'registry-storage-class'
      claimName: 'registry-pvc'