apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 32211
  selector:
    app: docker-registry
  type: LoadBalancer