apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.conf.dockerRegistry.name }}
  labels:
    app: {{ .Values.conf.dockerRegistry.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 32211
  selector:
    app: {{ .Values.conf.dockerRegistry.name }}
  type: LoadBalancer