apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 32211
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32213
  selector:
    app: docker-registry
  type: LoadBalancer