apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.conf.dockerRegistryUi.name }}
  labels:
    app: {{ .Values.conf.dockerRegistryUi.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32213
  selector:
    app: {{ .Values.conf.dockerRegistryUi.name }}
  type: LoadBalancer
