apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.conf.dockerRegistry.name }}
  labels:
    app: {{ .Values.conf.dockerRegistry.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.conf.dockerRegistry.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.conf.dockerRegistry.name }}
    spec:
      hostname: {{ .Values.conf.dockerRegistry.name }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.conf.dockerRegistry.pv.storageName }}
          persistentVolumeClaim:
            claimName: {{ .Values.conf.dockerRegistry.pv.claimName }}
      containers:
        - env:
            - name: DOCKER_REGISTRY_URL
              value: http://localhost:5000
        - name: {{ .Values.conf.dockerRegistryUi.name }}
          image: klausmeyer/docker-registry-browser
          ports:
            - containerPort: 8080
          resources: {}
        - name: {{ .Values.conf.dockerRegistry.name }}
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: {{ .Values.conf.dockerRegistry.pv.storageName }}
              mountPath: /var/lib/registry