apiVersion: v1
kind: Service
metadata:
    name: nfs-server
    labels:
        app: nfs-server
    namespace: {{ .Values.deployment.namespace }}
spec:
    clusterIP: 10.152.183.221
    ports:
        - name: nfs
          port: 2049
          targetPort: 2049
        - name: mountd
          port: 20048
          targetPort: 20048
        - name: rpcbind
          port: 111
          targetPort: 111
    selector:
        app: nfs-server
    type: LoadBalancer