apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nfs-busybox
spec:
    replicas: 1
    selector:
        matchLabels:
            name: nfs-busybox
    template:
        metadata:
            labels:
                name: nfs-busybox
        spec:
            containers:
                - image: busybox
                  imagePullPolicy: Always
                  name: busybox
                  volumeMounts:
                      # name must match the volume name below
                      - name: nfs-volume
                        mountPath: "/mnt"
            volumes:
                - name: nfs-volume
                  nfs:
                      # URL for the NFS server
                      server: nfs-server # Change this!
                      path: /